declare namespace Icons {
  type Icon =
  'account' |
  'alarm-plus' |
  'alarm' |
  'alert-circle' |
  'alert-octagon' |
  'alert' |
  'arrange-bring-forward' |
  'arrange-bring-to-front' |
  'arrange-send-backward' |
  'arrange-send-to-back' |
  'arrow-down-circle' |
  'arrow-down' |
  'arrow-left-circle' |
  'arrow-left' |
  'arrow-right-circle' |
  'arrow-right' |
  'arrow-up-circle' |
  'arrow-up' |
  'bank' |
  'bell-off' |
  'bell' |
  'bluetooth' |
  'book-multiple' |
  'book-plus' |
  'book' |
  'bookmark' |
  'border-all' |
  'border-bottom' |
  'border-horizontal' |
  'border-inside' |
  'border-left' |
  'border-none' |
  'border-outside' |
  'border-right' |
  'border-top' |
  'border-vertical' |
  'briefcase' |
  'calendar' |
  'camcorder' |
  'camera' |
  'cancel' |
  'cart' |
  'chart-areaspline' |
  'chart-bar' |
  'chart-histogram' |
  'chart-line' |
  'chart-pie' |
  'check' |
  'chevron-double-down' |
  'chevron-double-left' |
  'chevron-double-right' |
  'chevron-double-up' |
  'chevron-down' |
  'chevron-left' |
  'chevron-right' |
  'chevron-up' |
  'clipboard-check' |
  'clipboard-plus' |
  'clipboard-text' |
  'clipboard' |
  'clock' |
  'closed-caption' |
  'cloud-download' |
  'cloud-upload' |
  'cloud' |
  'comment-alert' |
  'comment-text' |
  'comment' |
  'console' |
  'content-cut' |
  'content-duplicate' |
  'content-paste' |
  'content-save-all' |
  'content-save' |
  'credit-card' |
  'crop-free' |
  'crop' |
  'currency-eur' |
  'currency-gbp' |
  'currency-rub' |
  'currency-usd' |
  'delete' |
  'diamond' |
  'dots-horizontal' |
  'dots-vertical' |
  'download' |
  'eject' |
  'email-open' |
  'email' |
  'eye-off' |
  'eye' |
  'factory' |
  'fast-forward' |
  'file-multiple' |
  'file-plus' |
  'file' |
  'flag' |
  'flash' |
  'flask-empty' |
  'flask' |
  'folder-multiple' |
  'folder-plus' |
  'folder' |
  'format-align-bottom' |
  'format-align-center' |
  'format-align-justify' |
  'format-align-left' |
  'format-align-middle' |
  'format-align-right' |
  'format-align-top' |
  'format-bold' |
  'format-clear' |
  'format-float-center' |
  'format-float-left' |
  'format-float-none' |
  'format-float-right' |
  'format-indent-decrease' |
  'format-indent-increase' |
  'format-italic' |
  'format-line-spacing' |
  'format-list-bulleted' |
  'format-list-checks' |
  'format-list-numbers' |
  'format-quote-close' |
  'format-quote-open' |
  'format-underline' |
  'format-wrap-inline' |
  'format-wrap-square' |
  'format-wrap-tight' |
  'format-wrap-top-bottom' |
  'forum' |
  'fullscreen-close' |
  'fullscreen' |
  'gift' |
  'grid-large' |
  'grid-off' |
  'grid' |
  'group' |
  'hamburger' |
  'heart-half' |
  'heart-off' |
  'heart' |
  'help-circle' |
  'help' |
  'home' |
  'inbox' |
  'information' |
  'label' |
  'layers' |
  'lightbulb-on' |
  'lightbulb' |
  'link-variant' |
  'link' |
  'lock-unlocked' |
  'lock' |
  'login' |
  'logout' |
  'magnify-minus' |
  'magnify-plus' |
  'magnify' |
  'map-marker' |
  'memory' |
  'menu' |
  'message-alert' |
  'message-photo' |
  'message-processing' |
  'message-reply' |
  'message-text' |
  'message-video' |
  'message' |
  'microphone-off' |
  'microphone' |
  'minus-box' |
  'minus-circle' |
  'minus' |
  'monitor-multiple' |
  'monitor' |
  'music-off' |
  'music' |
  'nfc' |
  'note-multiple' |
  'note-plus' |
  'note-text' |
  'note' |
  'paperclip' |
  'pause' |
  'pencil' |
  'phone' |
  'picture' |
  'pin-off' |
  'pin' |
  'play' |
  'plus-box' |
  'plus-circle' |
  'plus' |
  'power' |
  'presentation-play' |
  'presentation' |
  'printer' |
  'redo-variant' |
  'refresh' |
  'repeat-off' |
  'repeat-once' |
  'repeat' |
  'rewind' |
  'rss' |
  'script' |
  'seek-next' |
  'seek-previous' |
  'settings' |
  'shape-circle' |
  'shape-hexagon' |
  'shape-octagon' |
  'shape-rhombus' |
  'shape-square' |
  'shape-triangle' |
  'shield' |
  'shuffle' |
  'signal' |
  'sitemap' |
  'sleep-off' |
  'sleep' |
  'spellcheck' |
  'star-half' |
  'star' |
  'stop' |
  'tab-plus' |
  'tab' |
  'table' |
  'taco' |
  'tag' |
  'television' |
  'thumb-down' |
  'thumb-up' |
  'thumbs-up-down' |
  'tooltip-text' |
  'tooltip' |
  'trophy' |
  'undo-variant' |
  'unfold-less-horizontal' |
  'unfold-less-vertical' |
  'unfold-more-horizontal' |
  'unfold-more-vertical' |
  'ungroup' |
  'upload' |
  'view-dashboard' |
  'view-module' |
  'volume-minus' |
  'volume-mute' |
  'volume-off' |
  'volume-plus' |
  'volume' |
  'wifi' |
  'xml'
}
