import h from 'helix-react/lib/html'
import { Models } from '../model'
import Button from '../components/button'
import Carousel from '../components/carousel'

const page: Helix.Page<Models> = {
  onEnter(_state, _prev, actions) {
    actions.products.fetchAll()
  },
  view(state, prev, actions) {
    return (
      <div>
        <Carousel
          autoPlay={5000}
          key='about-carousel'
          items={[
            '/assets/images/about-1.jpg',
            '/assets/images/about-2.jpg',
            '/assets/images/about-3.jpg',
            '/assets/images/about-4.jpg',
            '/assets/images/about-5.jpg',
          ]}
          item={img => {
            return (
              <div>
                <div
                  className='h-10 d-flex flex-direction-column'
                  style={{
                    backgroundImage: `url(${img})`,
                    backgroundPosition: 'center center',
                    backgroundSize: 'cover',
                    backgroundRepeat: 'no-repeat',
                  }}
                />
              </div>
            )
          }}
        />
        <div className='mb-6'>
          <p className='mb-3 lh-5'>
            Rise Bakery is a thriving social enterprise in East London which is part of
            homelessness charity, Providence Row. It combines a structured ten-week
            baking training scheme for people affected by homelessness with an online
            luxury brownie business. We deliver brownies in letter-box friendly packages
            all across the country to corporates, retail customers, cafes and markets.
          </p>

          <p className='mb-3 lh-5'>
            Rise Bakery's focus is on preparing people for work while helping with drug,
            alcohol and mental health support. We recognise that employment is one of the
            main ways out of homelessness, providing an opportunity to develop baking skills,
            experience working in a busy kitchen and be creative. All of which is useful
            while trying to get a job.
          </p>

          <p className='mb-3 lh-5'>
            All of the revenue generated by the business is invested back in to the training
            programme. This means we can continue to support trainees in their journey
            towards hope and a future in employment.
          </p>

          <Button
            label='Read our Blog'
            href='/blog'
            size='large'
            className='bra-pill w-100 ta-c'
          />
        </div>
      </div>
    )
  },
}

export default page
